version: '3'

services:
  flask:
    build:
      context: src
      args:
        - PYTHON_VERSION=python:3.8-slim
    image: christopherbasketfield/flask_app
    restart: always
    depends_on:
      - redis
    ports:
      - '5000:5000'

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  redis:
    image: redis:alpine
    command: redis-server --requirepass SeCrEtPaSsWoRd
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
