version: '3'

services:
  flask:
    build: flask_app
    restart: always
    depends_on: 
      - redis
    ports:
      - '8080:8080'
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - default_network

  redis:
    image: redis:alpine
    command: redis-server --requirepass SeCrEtPaSsWoRd
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  default_network:
    driver: bridge
