version: '3'

services:
  flask:
    build: flask_app
    restart: always
    depends_on: 
      - redis
    ports:
      - '8080:8080'
  nginx:
    build: nginx
    restart: always
    ports:
      - '80:80'
  redis:
    image: redis:alpine
    command: redis-server --requirepass SeCrEtPaSsWoRd
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
