version: '3'

services:
  flask:
    image: christopherbasketfield/flask_app
    build:
      context: flask
      args:
        - PYTHON_VERSION=python:3.8-slim
    restart: always
    depends_on:
      - redis
    ports:
      - '5000:5000'

  nginx:
    image: christopherbasketfield/nginx_flask_proxy
    build:
      context: nginx
    restart: always
    ports:
      - '80:80'

  redis:
    image: redis:alpine
    command: redis-server --requirepass SeCrEtPaSsWoRd
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
