version: '3'

services:
  flask:
    build: flask_app
    restart: always
    depends_on: 
      - redis
    ports:
      - '8080:8080'
  nginx:
    build: nginx
    restart: always
    ports:
      - '80:80'
  redis:
    image: redis:alpine
    command: redis-server --requirepass SeCrEtPaSsWoRd
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis-data:
    driver: local
